---
- name: provision
  hosts: localhost
  connection: local
  tasks:
    - name: add host
      ansible.builtin.add_host:
        name: '192.168.7.5'
        ansible_host: '192.168.7.5'
        groups: just_created
        
- name: configure
  hosts: just_created
  connection: ssh
  tasks:
    - name: debug
      debug:
        msg: "{{ ansible_host }}"
    - name: ping
      ping:
